# Generated by Django 5.2.18 on 2026-10-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('nombre_comercial', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion_principal', models.CharField(max_length=300)),
                ('distrito', models.CharField(max_length=120)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'db_table': 'clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('razon_social', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion_principal', models.CharField(max_length=300)),
                ('distrito', models.CharField(max_length=120)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'verbose_name': 'empresa',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Geocerca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('poligono', models.JSONField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'geocerca',
                'db_table': 'geocercas',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('aplica_a', models.CharField(choices=[('NO_LLEGO', 'No llegó'), ('SERVICIO_FALLIDO', 'Servicio fallido'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'motivo',
                'db_table': 'motivos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('capacidad_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'vehículo',
                'db_table': 'vehiculos',
                'ordering': ['placa'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESTINOS', 'Destinos'), ('RUTAS', 'Rutas')], max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('mapeo_columnas', models.JSONField(default=dict)),
                ('activa', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='catalogos.cliente')),
            ],
            options={
                'verbose_name': 'plantilla de importación',
                'db_table': 'plantillas_importacion',
                'constraints': [models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('cliente', 'tipo'), name='uniq_plantilla_activa')],
            },
        ),
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('distrito', models.CharField(max_length=120)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('es_principal', models.BooleanField(default=False)),
                ('es_base_origen', models.BooleanField(default=False)),
                ('es_sede', models.BooleanField(default=False)),
                ('es_base_final', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='catalogos.cliente')),
            ],
            options={
                'verbose_name': 'punto',
                'db_table': 'puntos',
                'constraints': [models.UniqueConstraint(condition=models.Q(('cliente__isnull', False), models.Q(('codigo', ''), _negated=True)), fields=('cliente', 'codigo'), name='uniq_punto_codigo_por_cliente'), models.UniqueConstraint(condition=models.Q(('cliente__isnull', True), models.Q(('codigo', ''), _negated=True)), fields=('codigo',), name='uniq_punto_codigo_varpal'), models.UniqueConstraint(condition=models.Q(('cliente__isnull', False), ('es_principal', True)), fields=('cliente',), name='uniq_punto_principal_cliente'), models.UniqueConstraint(condition=models.Q(('cliente__isnull', True), ('es_principal', True)), fields=('es_principal',), name='uniq_punto_principal_varpal')],
            },
        ),
    ]
