# Generated by Django 5.2.18 on 2026-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_cliente_latitud_alter_cliente_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='punto',
            name='latitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='punto',
            name='longitud',
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
