# Generated by Django 5.2.18 on 2026-10-07 02:51

import django.db.models.deletion
import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=operaciones.models.ruta_evidencia)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidencias',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RUTA_INICIADA', 'Ruta iniciada')], max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('precision_metros', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('rumbo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posiciones',
                'ordering': ['registrado_en'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('NO_INICIADA', 'No iniciada'), ('EN_PROCESO', 'En proceso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('llegada_base_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('distancia_metros', models.PositiveIntegerField(default=0)),
                ('duracion_segundos', models.PositiveIntegerField(default=0)),
                ('geometria_empresa', models.JSONField(blank=True, default=dict)),
                ('geometria_cliente', models.JSONField(blank=True, default=dict)),
                ('dentro_de_lima', models.BooleanField(default=False)),
                ('ultima_latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ultima_posicion_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ruta',
                'db_table': 'rutas',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RutaAuxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ruta_auxiliares',
            },
        ),
        migrations.CreateModel(
            name='RutaDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('hora_estimada', models.DateTimeField(blank=True, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ruta_destinos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('codigo_externo', models.CharField(max_length=60)),
                ('tipo_servicio', models.CharField(choices=[('ENTREGA', 'Entrega'), ('INTERCAMBIO', 'Intercambio'), ('RECOJO', 'Recojo'), ('TRASLADO', 'Traslado')], max_length=20)),
                ('documento_receptor', models.CharField(blank=True, max_length=20)),
                ('nombre_receptor', models.CharField(blank=True, max_length=150)),
                ('apellido_receptor', models.CharField(blank=True, max_length=150)),
                ('telefono_receptor', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(max_length=300)),
                ('distrito', models.CharField(max_length=120)),
                ('referencia', models.CharField(blank=True, max_length=300)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('motivo_servicio', models.TextField()),
                ('observaciones', models.TextField(blank=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('estado', models.CharField(choices=[('NO_INICIADO', 'No iniciado'), ('EN_PROCESO', 'En proceso'), ('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], default='NO_INICIADO', max_length=20)),
                ('observacion_cierre', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='catalogos.cliente')),
            ],
            options={
                'verbose_name': 'destino',
                'db_table': 'destinos',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
