# Generated by Django 5.2.18 on 2026-10-07 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destino',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='catalogos.motivo'),
        ),
        migrations.AddField(
            model_name='destino',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos_sede', to='catalogos.punto'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='operaciones.destino'),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='subido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruta',
            name='base_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_final', to='catalogos.punto'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='base_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_origen', to='catalogos.punto'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='catalogos.cliente'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='conductor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_conductor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruta',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='catalogos.vehiculo'),
        ),
        migrations.AddField(
            model_name='posicion',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='operaciones.ruta'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='operaciones.ruta'),
        ),
        migrations.AddField(
            model_name='rutaauxiliar',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliares', to='operaciones.ruta'),
        ),
        migrations.AddField(
            model_name='rutaauxiliar',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas_auxiliar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutadestino',
            name='destino',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion', to='operaciones.destino'),
        ),
        migrations.AddField(
            model_name='rutadestino',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='operaciones.ruta'),
        ),
        migrations.AddIndex(
            model_name='destino',
            index=models.Index(fields=['cliente', 'fecha', 'estado'], name='destinos_cliente_2e9473_idx'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.UniqueConstraint(fields=('cliente', 'codigo_externo'), name='uniq_destino_codigo_cliente'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'FALLIDO'), _negated=True), ('motivo__isnull', False), _connector='OR'), name='destino_fallido_tiene_motivo'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['cliente', 'fecha'], name='rutas_cliente_d18e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['conductor', 'estado'], name='rutas_conduct_8ac492_idx'),
        ),
        migrations.AddIndex(
            model_name='ruta',
            index=models.Index(fields=['estado', 'dentro_de_lima'], name='rutas_estado_c09de9_idx'),
        ),
        migrations.AddIndex(
            model_name='posicion',
            index=models.Index(fields=['ruta', 'registrado_en'], name='posiciones_ruta_id_099e54_idx'),
        ),
        migrations.AddConstraint(
            model_name='rutaauxiliar',
            constraint=models.UniqueConstraint(fields=('ruta', 'usuario'), name='uniq_ruta_auxiliar'),
        ),
        migrations.AddConstraint(
            model_name='rutadestino',
            constraint=models.UniqueConstraint(fields=('ruta', 'orden'), name='uniq_ruta_orden'),
        ),
    ]
