# Generated by Django 5.2.18 on 2026-10-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='latitud',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='destino',
            name='longitud',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='latitud',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='posicion',
            name='longitud',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ultima_latitud',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='ultima_longitud',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True),
        ),
    ]
